stages:
  - build
  - scan
  - push

variables:
  NEXUS_URL: "http://172.23.11.110:8081"
  APP_NAME: "fan-backend"

build:
  stage: build
  script:
    - pip install -r requirements.txt --index-url http://$nexus_user:$nexus_pass@172.23.11.110:8081/repository/pypi-proxy/simple/ --trusted-host 172.23.11.110 --timeout 120
    - pip download -r requirements.txt -d ./packages --timeout 120
  artifacts:
    paths:
      - packages/
    expire_in: 1 hour

iq-scan:
  stage: scan
  script:
    - curl -u ${nexus_user}:${nexus_pass} --output nexus-iq-cli.jar http://172.23.11.110:8081/repository/raw-hosted/tools/nexus-iq-cli.jar
    - java -jar nexus-iq-cli.jar -s $iq_url -a ${iq_user}:${iq_pass} -i $iq_app_id -t build ./packages
  dependencies:
    - build

push-to-nexus:
  stage: push
  script:
    - Compress-Archive -Path * -DestinationPath ${APP_NAME}-${CI_COMMIT_SHA}.zip -Force
    - curl -u ${nexus_user}:${nexus_pass} --upload-file ${APP_NAME}-${CI_COMMIT_SHA}.zip ${NEXUS_URL}/repository/raw-hosted/${APP_NAME}/${APP_NAME}-${CI_COMMIT_SHA}.zip
  only:
    - main
  dependencies:
    - build